### ISSUE TITLE
Tutorial para el uso de GitHub y Git

### ISSUE THREAD

**Issue by ninioArtillero** [ninioArtillero/Libro---Seminario-Perm.-de-Tec.-Musical#1]
Describir como vamos a trabajar en este entorno.
Definir las categorías de git que serán relevantes: pull, push, commit, branch, etc.

Propuesta: añadir al README frontal

**Comment by EmilioOcelotl** [comment]
Dos asuntos: 

1. ¿Realizaremos un branch para cada usuario y de cada rama vamos a solicitar PR par mantener actualizado el branch principal ? Una posible alternativa sería que cada quién hiciera un fork y luego PR al branch principal para mantenerlo lo más actualizado posible. 

2. Creo que puede ser bueno introducir discusiones sobre los términos de las ramas. En específico me gustaría problematizar el uso de master, recientemente algunas plataformas han decidido nombrar como main a la rama prinicipal de los proyectos.

**Comment by ninioArtillero** [comment]
Por asunto:
1. No entiendo la incidencia en el resultado de tomar uno u otro camino. Entiendo que el Fork tiene independencia del repositorio, mientras el Branch es "local" a este. Si en ambos casos el master es "alimentado" por los PR, ¿Cúal sería la ventaja de uno u otro?
* Por otro lado pienso que, contrario a la propuesta original del tutorial (cuyo proposito es también introducir los conceptos de git), se podría trabajar haciendo *push* directo para el trabajo propio y *fork* o *branch* (sigo con la duda anterior) para proponer ediciones/adiciones al trabajo ajeno. Al respecto encontré este [artículo](https://oleb.net/blog/2016/02/collaborative-writing-on-github/) con experiencias relacionadas.
2. Definitivamente es pertienente abrir los términos, aunque en lo personal no veo por donde empezar esa problematización. A primera vista me parece que tanto "main" como "master" responden a un orden jerárquico: siendo git un *sistema de control* de versiones ¿esto es problematizable? O tal vez la cuestión está en otro lado: ¿Cuáles son los matices que podrían inclinarnos por uno u otro? También podríamos tomar la palabra "tronco" (siendo que ya se tiene *branch*) o alguna otra alternativa pero me inclino a mantener relación con alguna convención de la comunidad (¿o iniciar nuestra convención?).

**Comment by ninioArtillero** [comment]
¡Ah! No vi que hablabas también de los términos de las ramas en general. Eso típicamente es una convención por proyecto (por lo que he leído). Veo que al respecto en general se maneja llamarlas por la caracteristica (feature o fix o experimento) particular que se trabajará en la rama. ¿Propones una alternativa para nosotros? Por cierto, está discusión podría seguir en un nuevo issue sobre "convenciones" o en el que abrí recientemente de "flujo de trabajo" pues veo que el decidir términos para las ramas implica haber decidido sobre como las vamos a usar.
