### ISSUE TITLE
Sobre el diseño del flujo de trabajo

### ISSUE THREAD

**Issue by ninioArtillero** [ninioArtillero/Libro---Seminario-Perm.-de-Tec.-Musical#4]
Para hacer valer el ejercicio de trabajar los textos usando git+GitHub, considero que hay que contestar:

1. ¿Cómo se va a organizar la actualización del repositorio?

2. ¿Cómo nos benefician las funciones de esta herramienta?

De momento en el tutorial propuse la creación de branches para trabajar, pensando en poner en práctica eso. Sin embargo, por lo que he estado investigado, se me ocurre estas ideas para workflow (1):

1. En el caso de trabajo personal hacer push directo al repo.
2. En el caso de querer trabajar sobre el artículo de otro autor o grupo de trabajo (para corrección de estilo, caza de erratas o colaboración): hacer un branch y luego el pull request sería evaluado por el autor/grupo de trabajo correspondiente.

Respecto a (2) quisiera oir las opiniones de quienes tengas más experiencia en esta plataforma. Me preocupa que mi propio interés (práctico y teórico) en git pueda ser un *bias* en mi apreciación de su relevancia o aplicabilidad para las necesidades de este proyecto. De entrada me parece que permite un acercamiento "respetuoso" a manipular los textos ajenos y llevar un historial de versiones conforme se organicen rondas de revisión.

**Comment by rexmalebka** [comment]
Como buena práctica está bien tener branches separados y hacer merge a master siempre desde un PR, así todos pueden ver y escribir comentarios sobre los cambios y si suceden errores no se dañe master directamente.

y pues para crear un branch nuevo, haciendo siempre checkout desde master, así los nuevos branches siempre estarían limpios.

**Comment by rexmalebka** [comment]
en general:

- cada quien trabaje en archivos separados para limitar la cantidad de errores
- que los branches procedan siempre desde master
- que solo se haga push a master desde un PR, en caso de que alguien intente sobreescribir los cambios de alguien mas, hay más control sobre las correcciones

**Comment by ninioArtillero** [comment]
Muchas gracias por el aporte Dorian. Una duda sobre este flujo y uso de los branches: después de hacer PR y sea aprobado el merge, ¿vale la pena continuar trabajando en ese branch o conviene borrarlo? ¿Puedes desarrollar un poco por qué? 

Inicialmente pensé (antes de esa potencialmente peligrosa idea del push directo al master) que el workflow más conveniente era armar un "branch personal", desde donde se hiciera PR cada vez que se tenía un aporte listo para ser revisado por los demás. ¿Qué opinas?

**Comment by hvillase** [comment]
Hola, hemos estado trabajando con Aarón en nusetras respectivas _branch_  y luego hacemos merge entre branches y salió el tema de cómo hacer esto con los demás intergrantes. Justo lo que dice Dorian de hacer una _branch_ desde el master y luego hacer _pull request_. Pero antes de hacer esta branch ¿no tendríamos que hacer primero un fork en nuestro repo personal para de ahí hacer la rama? Pro lo pronto yo ya cloné la rama master en mi computadora he hice unos cambios. Voy a hacer un pull request a ver qué pasa, pero tengo duda en ese paso de hacer primero el fork.

**Comment by rexmalebka** [comment]
Los forks garantizan copias en caso de que el central se elimine pero añade complejidad porque ahora tienes que jalar cambios del remoto y del tuyo ( en caso de que se hagas al tuyo), podrían tener la ventaja de que cada quien podría mantener su propia versión de master, aunque en algún momento tendría que actualizarse con el central, además de que eso no quitaría el paso del PR para evitar inconsistencias en el repo central.

Los forks se usan más cuando quieres hacer contribuciones y no formas parte de los programadores autorizados del repo, eventualmente podría añadir más capas de pasos que simplemente actualizar un solo master/main

Los branches una vez hecho merge pueden borrarse.

**Comment by rexmalebka** [comment]
Aunque de cierta manera da igual (mientras cada quien modifique su propio archivo), la procedencia del Pull request, ya sea si viene de un branch o si viene de un fork

**Comment by hvillase** [comment]
Perfecto, entonces me voy a clonar el _master_ tal cual está ahora para trabajar desde ahí

**Comment by ninioArtillero** [comment]
Procuraré tener mi clon local del *master* actualizado (haciendo *fetch* y luego *pull*) y de ahí haré el *branching* como sugiere @rexmalebka  para trabajar en el material que se vaya integrando. Por ahí en las fuentes del README frontal puse una pequeña guía de limpieza para ir quitando localmente las *branches* (con sus referencias) que ya no se ocupan.

Creo que falta acordar como vamos a aprobar los *pull-request* y cuando hacer la revisión colectiva antes del *merge*. En general creo que uno mismo lo puede hacer para edición de sus propios documentos, pero en otro caso ¿qué convendría? Bajo el supuesto de que hay comunicación fluida asumiría que no se harán cambios indeseables, pero ¿podríamos anticiparlo desde el workflow?

**Comment by rexmalebka** [comment]
hay una sección de branch protection donde le puedes especificar cuantos approvals necesitas para que se acepte un merge y también se puede agregar una protección para que no se pueda hacer merge a menos que el cambio esté actualizado en relación a la rama principal (recomendaría esta última restricción).

ya nomás sería de ponerse de acuerdo para definir si quieren que se aagreguen approvals y así.

**Comment by ninioArtillero** [comment]
Parece que, para repos privados, esas opciones requieren una cuenta de githup con costo. Tendremos que acordar algún protocolo simple para regular los merges (o no). Se podría simplemente añadir un comentario al PR cuando concierna a algún equipo lo autor.
